[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "Mononoki Nerd Font"

size = 18

# Default colors
[colors.primary]
  background = "#212337"
  foreground = "#ebfafa"

# Normal colors
[colors.normal]
  black = "#292d3e"
  red = "#f07178"
  green = "#c3e88d"
  yellow = "#ffcb6b"
  blue = "#82aaff"
  magenta = "#c792ea"
  cyan = "#89ddff"
  white = "#d0d0d0"

# Bright colors
[colors.bright]
  black = "#434758"
  red = "#ff8b92"
  green = "#ddffa7"
  yellow = "#ffe585"
  blue = "#9cc4ff"
  magenta = "#e1acff"
  cyan = "#a3f7ff"
  white = "#ffffff"
